version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.36.0
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: "text2vec-ollama"
      DEFAULT_VECTORIZER_MODULE: "text2vec-ollama"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    volumes:
      - weaviate_data:/var/lib/weaviate
    depends_on:
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama   

volumes:
  weaviate_data:
  ollama_data: